### PR TITLE
Fix TargetedMSQCGuideSetTest - update to recognize new page when query doesn't exist

### PR DESCRIPTION
**Pull request by labkey-jeckels**

### CODE REVIEW

**Comment by labkey-tchad** [comment]
Waiting for TargetedMS suite:
https://teamcity.labkey.org/viewQueued.html?itemId=763513
https://teamcity.labkey.org/viewQueued.html?itemId=763515

**Comment by labkey-tchad** [comment]
@labkey-jeckels Was this intended to be branched from fb_qcNotifications or was that an accident?

**Comment by labkey-jeckels** [comment]
@labkey-tchad It was an accident. I thought I had switched back to develop before creating it, but evidently not. Will it be easiest to delete this branch and recreate?

**Comment by labkey-tchad** [comment]
@labkey-jeckels You could also run `git rebase --onto origin/develop fb_qcNotifications fb_fixQueryExistenceCheck` if you're feeling adventurous.

**Pull request closed without merging**
