### PR TITLE
22.11 fb bilinear regression fit

### PR DESCRIPTION
**Pull request by nickshulman**
Need to be fixed before merging: the calibration curve graph always draws as a straight line, even though the line for "Bilinear"  is supposed to be two straight lines with a turn in it, and "Linear in log space" produces a line which is curved when plotted on a linear graph.
image

#### Rationale
Issue 43922: Add support for "Linear in Log Space" and "Bilinear" regression fit options

#### Changes
Add support for "Bilinear" and "Linear in Log Space" regression fit values.

### CODE REVIEW

**Comment by labkey-jeckels** [comment]
@nickshulman let me know if you want help on updating the plots

**Comment by labkey-jeckels** [comment]
@nickshulman what are the next steps on this PR. Do you want us to handle anything on the LabKey side?

**Comment by nickshulman** [comment]
I think we should wait a month before committing this fix.
I have to change the implementation of the bilinear regression in Skyline 23.1. After I implement the changes in Skyline I will change this pull request so that it uses the new algorithm.
(The new algorithm puts the bend in the curve at the location which is the mean of the data points below that curve. The algorithm in this pull request uses a Nelder Mead Simplex to find  the value which would result in the lowest R-squared.)

**Comment by labkey-jeckels** [comment]
Sounds good. Thanks for the update.

**Comment by labkey-jeckels** [comment]
@nickshulman Any updates on your schedule here? Have you had a chance to make the Skyline updates yet?

**Comment by labkey-jeckels** [comment]
@nickshulman any updates on the timing for this? @brendanx67

**Comment by nickshulman** [comment]
> @nickshulman any updates on the timing for this? @brendanx67

Probably beginning of May.
Skyline code complete is scheduled for end of April, so it will have the new bilinear curve fit algorithm by then, and I will then be able to implement that algorithm in Panorama shortly after that.

**Comment by labkey-jeckels** [comment]
@nickshulman any updates on this? Brendan mentioned this may be at risk for 23.1.

**Comment by labkey-jeckels** [comment]
@nickshulman is this the PR on the Skyline side that we can follow the progress and not need to nag you periodically?

https://github.com/ProteoWizard/pwiz/pull/2572

**Comment by nickshulman** [comment]
> @nickshulman is this the PR on the Skyline side that we can follow the progress and not need to nag you periodically?
> 
> [ProteoWizard/pwiz#2572](https://github.com/ProteoWizard/pwiz/pull/2572)

Yes, that's the PR on the Skyline side.

**Comment by nickshulman** [comment]
Need to re-create this pull request with a different branch name targeting develop.

**Comment by labkey-jeckels** [comment]
@nickshulman we already branched for 23.7, so you may want to use `23.7_fb_` so we can get it out before 23.11 in November.

**Pull request closed without merging**
