### PR TITLE
Automation test coverage for Issue 45544

### PR DESCRIPTION
**Pull request by labkey-sweta**
#### Rationale
Automation test for Issue 45544: Clicking "View Chromatogram" from Panorama QC plot doesn't page to show desired plot 

#### Related Pull Requests
* 

#### Changes
*

### CODE REVIEW

**Review by labkey-jeckels — CHANGES_REQUESTED** [review]
The new test case is failing on TeamCity. It probably needs some explicit scrolling.

Let's also click on at least two different points on the plot that take you to different pages of the chromatogram to get more robust coverage.

**Review by labkey-tchad — COMMENTED** [review]
I have nothing to add

**Comment by labkey-jeckels** [comment]
@labkey-sweta has this gotten lost?

**Comment by labkey-sweta** [comment]
> @labkey-sweta has this gotten lost?

Was working on develop, just came back to 22.3. Working on that today
Thank you

**Comment by labkey-jeckels** [comment]
@labkey-sweta I just added this to the board to help it move along. We may want to retarget to 22.7.

**Comment by labkey-sweta** [comment]
Closing this PR, renamed the fb to target 22.7 (22.7_fb_45544AutoTest)

**Pull request closed without merging**
