### PR TITLE
Issue 41317: conditionalize sql upgrade script to support older pg vesions

### PR DESCRIPTION
**Pull request by labkey-ankurj**
#### Rationale
See https://github.com/LabKey/targetedms/pull/246

### CODE REVIEW

**Review by labkey-tchad — APPROVED** [review]

**Review by labkey-tchad — APPROVED** [review]

**Comment by labkey-jeckels** [comment]
The Clustergrammer fixes are in develop already. I don't think it's worth backporting to 20.9 since the groups taking a 20.9 build aren't doing TargetedMS

**Comment by labkey-tchad** [comment]
> The Clustergrammer fixes are in develop already. I don't think it's worth backporting to 20.9 since the groups taking a 20.9 build aren't doing TargetedMS

They might not be using it but that the upgrade script will still run and fail. Targetedms is in most distributions.

**Comment by labkey-jeckels** [comment]
Yes, we still need to merge this change. I just meant we needn't worry about the TargetedMS failures that are being reported in this PR.

**Comment by labkey-ankurj** [comment]
thanks, merging this branch.

**Pull request merged**
